// GENERATED by scripts/gen-toolchain-hash.mjs — do not edit by hand.
// The §4.4 toolchainHash of the installed @immediately-run/transpiler (= the
// published tarball). Regenerated on every build (prebuild). The deploy asserts
// this equals the hash the CLI stamps into artifact indexes (G2-8).

export const EMBEDDED_TOOLCHAIN_HASH = '5d8930a43e2a5247e6ec951e5386d770d6cf46810f87ec6bcbdb3e053606d412';
