#!/usr/bin/env node
/*
 * One-shot transcription: the two Phase-1 snapshots → the descriptor set
 * (`descriptors.protocol.mjs`), which is the single source from R3-274b onward.
 *
 * WHY THIS EXISTS AS A COMMITTED SCRIPT AND NOT A THROWAWAY. The descriptors are
 * the source of truth going forward, so how they were first populated is a claim
 * that has to be auditable: they were TRANSCRIBED from the frozen snapshots, not
 * re-derived from someone's reading of the code. Re-running this against the
 * Phase-1 snapshots must reproduce the committed descriptors byte for byte — which
 * is also what makes the generator's byte-identity test meaningful rather than
 * circular (the generator projects descriptors back to snapshots; this projects
 * snapshots to descriptors; a lossy step anywhere breaks one of the two).
 *
 * Run: node scripts/protocol-codegen/transcribe.mjs [--check]
 *   --check   re-transcribe and fail if the committed descriptors differ
 *
 * After R3-274b, EDIT THE DESCRIPTORS, not the snapshots. This script is for
 * provenance and for the `--check` gate, not for round-tripping a snapshot edit
 * back into the source (a hand-edited snapshot fails `protocol:check` anyway).
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const sandboxSnapshot = join(root, 'protocol-snapshot.json');
// The SDK's snapshot. Once R3-274b has run, the in-repo PROJECTION is the input —
// no sibling checkout, so `--check` is safe to run in CI (a build that reads a
// sibling checkout is exactly what R3-274d exists to retire). The sibling path is
// the bootstrap fallback used once, to transcribe the SDK's hand-frozen Phase-1
// snapshot before any projection existed.
const sdkProjection = join(root, 'generated/sdk/protocol-snapshot.json');
const sdkSibling = join(root, '../immediately-run-sdk/protocol-snapshot.json');
const sdkSnapshot = existsSync(sdkProjection) ? sdkProjection : sdkSibling;
const outPath = join(here, 'descriptors.protocol.mjs');

const read = (p) => {
  if (!existsSync(p)) {
    console.error(`error: ${p} not found.`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(p, 'utf8'));
};

const sandbox = read(sandboxSnapshot);
const sdk = read(sdkSnapshot);

const names = [...new Set([...Object.keys(sandbox.channels), ...Object.keys(sdk.channels)])].sort();

/** `fs-change` → `FS_CHANGE`, `protocol-spaces` → `PROTOCOL_SPACES`. */
const constName = (wire) => wire.replace(/[^A-Za-z0-9]+/g, '_').toUpperCase();
/** `fs-change` → `FsChange` (the payload/type prefix). */
const typeName = (wire) =>
  wire
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('');

const channels = names.map((name) => {
  const a = sandbox.channels[name];
  const b = sdk.channels[name];
  const entry = {
    name,
    const: constName(name),
    type: typeName(name),
  };
  // The hand-authored divergence markers are channel-level facts, not per-side
  // ones — they are hoisted here so a single edit clears them in both projections
  // (R3-274e's exit criterion is "zero markers remain", in BOTH snapshots).
  const marker = a?.divergent ? a : b?.divergent ? b : undefined;
  if (marker) {
    entry.divergent = true;
    entry.divergentNote = marker.divergentNote;
  }
  if (a) entry.sandbox = a;
  if (b) entry.sdk = b;
  return entry;
});

const j = (v) => JSON.stringify(v, null, 2).split('\n').join('\n  ');

const body = `// GENERATED by scripts/protocol-codegen/transcribe.mjs from the R3-274 / R3-274a
// snapshots, then MAINTAINED BY HAND. This is the single source for the
// sandbox<->SDK wire vocabulary (PLATFORM_LAYERING_SPEC §2 / S1, target 1).
//
// Edit THIS file to change the wire. \`scripts/protocol-codegen/generate.mjs\`
// projects it into four artifacts:
//   src/generated/protocol.ts          the frame's constants + payload types
//   protocol-snapshot.json             this repo's snapshot (a PROJECTION now)
//   generated/sdk/protocol.ts          the SDK-side module (delivered to that repo)
//   generated/sdk/protocol-snapshot.json   the SDK's snapshot (a PROJECTION now)
//
// Per-channel \`sandbox\`/\`sdk\` blocks are that side's snapshot entry verbatim: a
// name only one side speaks has only one block (39 of these are SDK-only — the
// frame relays them and the host is the other end; see the R3-274a audit).
// \`divergent\` markers are hoisted to the channel so clearing one clears BOTH
// projections, which is what R3-274e has to be able to do in a single edit.

/** Snapshot format version both projections carry. */
export const FORMAT_VERSION = ${sandbox.formatVersion};

/** npm/package name each projection labels itself with. */
export const REPOS = {
  sandbox: ${JSON.stringify(sandbox.repo)},
  sdk: ${JSON.stringify(sdk.repo)},
};

/** The transport framing each side rides — snapshotted per side, not shared. */
export const ENVELOPES = {
  sandbox: ${j(sandbox.envelopes)},
  sdk: ${j(sdk.envelopes)},
};

/** Names minted from a template at runtime: the scheme LIST, never a wildcard. */
export const DYNAMIC_FAMILIES = {
  sandbox: ${j(sandbox.dynamicFamilies)},
  sdk: ${j(sdk.dynamicFamilies)},
};

/** Every wire name, sorted. */
export const CHANNELS = ${j(channels)};
`;

if (process.argv.includes('--check')) {
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
  if (current === body) {
    console.log(`PASS  descriptors.protocol.mjs is exactly the transcription of both snapshots.`);
    process.exit(0);
  }
  console.error('✗ descriptors.protocol.mjs differs from a fresh transcription of the snapshots.');
  console.error(
    '\nEither the descriptors were edited without regenerating (run\n' +
      '`node scripts/protocol-codegen/generate.mjs` and commit), or a snapshot was\n' +
      'hand-edited (it is generated — edit the descriptors instead).',
  );
  process.exit(1);
}

writeFileSync(outPath, body);
console.log(`✓ Wrote descriptors.protocol.mjs (${channels.length} channels).`);
